### ISSUE TITLE
Crashing when leaving area around spawn

### ISSUE THREAD

**Issue by Grugspro** [CubWatson/Nimura#2]
When leaving spawn area with lots of images and create devices, instance crashes, enter  spawn area is no issue, only leaving is

[crash-2024-10-18_23.18.17-client.txt](https://github.com/user-attachments/files/17442502/crash-2024-10-18_23.18.17-client.txt)

**Comment by CubWatson** [comment]
Hey, so it looks like NeoForge was causing issues with this version of create. Since NeoForge for 1.20.1 is not recommended to use anyway, I updated the modpack to forge v47.3.0 for 1.20.1.

Tested this on the priv server and it fixes the spawn crashes. Should be good to go now @Grugspro!

Hope that helps!

[Here's the version that fixes this issue. (2.6.0)](https://modrinth.com/modpack/nimura/version/2.6.0)
